name: har

on:
  push:
    branches:
      - master
      - ohos-arm32
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

  workflow_dispatch:

# env:
#   ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

concurrency:
  group: har-${{ github.ref }}
  cancel-in-progress: true

jobs:
  har:
    if: false
    name: Har
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update version
        shell: bash
        run: |
          ./new-release.sh
          git diff .

      - name: cache-toolchain
        id: cache-toolchain-ohos
        uses: actions/cache@v4
        with:
          path: command-line-tools-2
          key: commandline-tools-linux-x64-5.0.5.200.zip

      - name: Download toolchain
        if: steps.cache-toolchain-ohos.outputs.cache-hit != 'true'
        shell: bash
        run: |
          curl -SL -O https://huggingface.co/csukuangfj/harmonyos-commandline-tools/resolve/main/commandline-tools-linux-x64-5.0.5.200.zip
          unzip commandline-tools-linux-x64-5.0.5.200.zip
          rm commandline-tools-linux-x64-5.0.5.200.zip

          mv command-line-tools command-line-tools-2

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: har-linux

      - name: cache-toolchain (CPU)
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: command-line-tools
          key: ohos-sdk-windows_linux-public-5.0.0

      - name: Download toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        shell: bash
        run: |
          curl -L -O https://github.com/openharmony-rs/ohos-sdk/releases/download/v5.0.0/ohos-sdk-windows_linux-public.tar.gz.aa
          curl -L -O https://github.com/openharmony-rs/ohos-sdk/releases/download/v5.0.0/ohos-sdk-windows_linux-public.tar.gz.ab

          cat ohos-sdk-windows_linux-public.tar.gz.aa ohos-sdk-windows_linux-public.tar.gz.ab > ohos-sdk-windows_linux-public.tar.gz
          tar -xzf ohos-sdk-windows_linux-public.tar.gz
          rm ohos-sdk-windows_linux-public.tar.gz*

          echo "---linux---"
          ls -lh linux

          echo "---windows---"
          ls -lh windows

          pushd linux/
          unzip native-linux-x64-5.0.0.71-Release.zip
          ls -lh native
          popd

          dst=command-line-tools/sdk/default/openharmony
          mkdir -p $dst

          mv linux/native $dst

          rm -rf linux windows

          ls

          echo "---"

          ls -lh $dst/

      - name: Set environment variable
        shell: bash
        run: |
          echo "$GITHUB_WORKSPACE/command-line-tools/sdk/default/openharmony/native/build-tools/cmake/bin"  >> "$GITHUB_PATH"
          which cmake

          cmake --version

          ls -lh $GITHUB_WORKSPACE/command-line-tools/sdk/default/openharmony/native/build/cmake/ohos.toolchain.cmake

          echo "===="
          cat $GITHUB_WORKSPACE/command-line-tools/sdk/default/openharmony/native/build/cmake/ohos.toolchain.cmake
          echo "===="

          # echo "$GITHUB_WORKSPACE/command-line-tools/sdk/default/openharmony/native/llvm/bin"  >> "$GITHUB_PATH"

          ls -lh $GITHUB_WORKSPACE/command-line-tools/sdk/default/openharmony/native/llvm/bin/
          echo "--"
          ls -lh $GITHUB_WORKSPACE/command-line-tools/sdk/default/openharmony/native/llvm/bin/*unknown*

          cat $GITHUB_PATH

          # /home/runner/work/onnxruntime-libs/onnxruntime-libs/command-line-tools/sdk/default/openharmony/native/llvm/bin/aarch64-unknown-linux-ohos-clang -v || true
          export PATH=$PWD/command-line-tools/sdk/default/openharmony/native/llvm/bin:$PATH
          echo "path: $PATH"

          which aarch64-unknown-linux-ohos-clang++ || true
          which aarch64-unknown-linux-ohos-clang || true

          aarch64-unknown-linux-ohos-clang++ --version || true
          aarch64-unknown-linux-ohos-clang --version || true

          which armv7-unknown-linux-ohos-clang++
          which armv7-unknown-linux-ohos-clang

          armv7-unknown-linux-ohos-clang++ --version
          armv7-unknown-linux-ohos-clang --version

          which x86_64-unknown-linux-ohos-clang++
          which x86_64-unknown-linux-ohos-clang

          x86_64-unknown-linux-ohos-clang++ --version
          x86_64-unknown-linux-ohos-clang --version

      - name: Patch toolchain file
        shell: bash
        run: |
          toolchain_file=$GITHUB_WORKSPACE/command-line-tools/sdk/default/openharmony/native/build/cmake/ohos.toolchain.cmake
          sed -i.bak 's/set(UNIX TRUE CACHE BOOL FROCE)/set(UNIX TRUE CACHE BOOL "Force UNIX" FORCE)/g' $toolchain_file

          sed -i.bak s/CMAKE_SYSTEM_NAME\ OHOS/CMAKE_SYSTEM_NAME\ Linux/g $toolchain_file
          # Add __OHOS__ define to the toolchain so all source files see it
          sed -i.bak 's/set(CMAKE_C_FLAGS "${OHOS_C_COMPILER_FLAGS} ${CMAKE_C_FLAGS} -D__MUSL__")/set(CMAKE_C_FLAGS "${OHOS_C_COMPILER_FLAGS} ${CMAKE_C_FLAGS} -D__MUSL__ -D__OHOS__")/' $toolchain_file
          sed -i.bak 's/set(CMAKE_CXX_FLAGS "${OHOS_CXX_COMPILER_FLAGS} ${CMAKE_CXX_FLAGS} -D__MUSL__")/set(CMAKE_CXX_FLAGS "${OHOS_CXX_COMPILER_FLAGS} ${CMAKE_CXX_FLAGS} -D__MUSL__ -D__OHOS__")/' $toolchain_file

          echo "---"

          cat $toolchain_file

      - uses: actions/upload-artifact@v4
        with:
          name: sherpa-onnx-ohos-toolchain-file-${{ matrix.arch }}
          path: command-line-tools/sdk/default/openharmony/native/build/cmake/ohos.toolchain.cmake

      - name: Install tree
        shell: bash
        run: |
          sudo apt-get update -q
          sudo apt-get install -y -q tree

      - name: Build libraries
        shell: bash
        run: |
          export CMAKE_CXX_COMPILER_LAUNCHER=ccache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          cmake --version

          export OHOS_SDK_NATIVE_DIR="$GITHUB_WORKSPACE/command-line-tools/sdk/default/openharmony/native"

          ./build-ohos-armeabi-v7a.sh
          ./build-ohos-arm64-v8a.sh
          ./build-ohos-x86-64.sh

      - name: Patch build-profile for OpenHarmony ARM32 Test
        if: false
        run: |
          sed -i 's/"x86_64"/"x86_64",/g' harmony-os/SherpaOnnxHar/sherpa_onnx/build-profile.json5

          sed -i '/"x86_64",/a \        "armeabi-v7a"' harmony-os/SherpaOnnxHar/sherpa_onnx/build-profile.json5

          echo "=== Modified build-profile.json5 ==="
          cat harmony-os/SherpaOnnxHar/sherpa_onnx/build-profile.json5

          git diff .

      - name: Build Har
        shell: bash
        run: |
          export PATH="$GITHUB_WORKSPACE/command-line-tools-2/bin:$PATH"

          which hvigorw

          pushd harmony-os/SherpaOnnxHar

          cp -fv ../../LICENSE ./sherpa_onnx
          cp -fv ../../CHANGELOG.md ./sherpa_onnx

          hvigorw --mode module -p product=default -p module=sherpa_onnx@default assembleHar --analyze=normal --parallel --incremental --no-daemon

          export HAR_PATH="$GITHUB_WORKSPACE/harmony-os/SherpaOnnxHar/sherpa_onnx/build/default/outputs/default/sherpa_onnx.har"

          ls -lh ./sherpa_onnx/build/default/outputs/default/sherpa_onnx.har

          mkdir -p $GITHUB_WORKSPACE/patch-workdir/libs/armeabi-v7a

          cp -v $GITHUB_WORKSPACE/harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/libs/armeabi-v7a/libonnxruntime.so $GITHUB_WORKSPACE/patch-workdir/libs/armeabi-v7a/
          cp -v $GITHUB_WORKSPACE/harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/libs/armeabi-v7a/libsherpa-onnx-c-api.so $GITHUB_WORKSPACE/patch-workdir/libs/armeabi-v7a/
          cp -v $GITHUB_WORKSPACE/command-line-tools-2/sdk/default/openharmony/native/llvm/lib/arm-linux-ohos/c++/a7_softfp_neon-vfpv4/libc++_shared.so $GITHUB_WORKSPACE/patch-workdir/libs/armeabi-v7a/

          cd $GITHUB_WORKSPACE/patch-workdir
          zip -ur "$HAR_PATH" libs/

          unzip -l "$HAR_PATH" | grep "libs/"

          cp -v "$HAR_PATH" $GITHUB_WORKSPACE/

      - name: Setup tmate session
        # if: true
        if: failure()
        uses: mxschmitt/action-tmate@v3

      - name: View Har
        shell: bash
        run: |
          file sherpa_onnx.har
          tar xvf sherpa_onnx.har

          cd package
          ls -lh

          ls -lh libs
          echo "---libs/x86_64---"
          ls -lh libs/x86_64

          echo "---libs/arm64-v8a---"
          ls -lh libs/arm64-v8a

          echo "---libs/armeabi-v7a---"
          ls -lh libs/armeabi-v7a

          echo "---src/main/ets/components---"
          ls -lh src/main/ets/components/

          echo "---src/main/cpp/types/libsherpa_onnx/---"
          ls -lh src/main/cpp/types/libsherpa_onnx/

          tree .

      - name: Collect result
        shell: bash
        run: |
          SHERPA_ONNX_VERSION=v$(grep "SHERPA_ONNX_VERSION" ./CMakeLists.txt  | cut -d " " -f 2  | cut -d '"' -f 2)
          echo "SHERPA_ONNX_VERSION=$SHERPA_ONNX_VERSION" >> "$GITHUB_ENV"

          mv sherpa_onnx.har sherpa_onnx-$SHERPA_ONNX_VERSION.har

      - uses: actions/upload-artifact@v4
        with:
          name: sherpa-onnx-har
          path: ./sherpa_onnx*.har

      - name: Release har
        # if: (github.repository_owner == 'csukuangfj' || github.repository_owner == 'k2-fsa') && github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          overwrite: true
          file: ./*.har
          repo_name: k2-fsa/sherpa-onnx
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: v1.13.3

      - name: Publish to huggingface
        # if: (github.repository_owner == 'csukuangfj' || github.repository_owner == 'k2-fsa') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        uses: nick-fields/retry@v3
        with:
          max_attempts: 20
          timeout_seconds: 200
          shell: bash
          command: |
            git config --global user.email "csukuangfj@gmail.com"
            git config --global user.name "Fangjun Kuang"

            rm -rf huggingface
            export GIT_LFS_SKIP_SMUDGE=1
            export GIT_CLONE_PROTECTION_ACTIVE=false

            SHERPA_ONNX_VERSION=$(grep "SHERPA_ONNX_VERSION" ./CMakeLists.txt  | cut -d " " -f 2  | cut -d '"' -f 2)
            echo "SHERPA_ONNX_VERSION $SHERPA_ONNX_VERSION"

            git clone https://csukuangfj2:$HF_TOKEN@huggingface.co/csukuangfj2/sherpa-onnx-harmony-os huggingface
            cd huggingface
            git fetch
            git pull
            git merge -m "merge remote" --ff origin main

            d=har
            mkdir -p $d
            cp -v ../*.har $d/
            git status
            git lfs track "*.har"
            git add .
            git commit -m "add more hars"
            git push https://csukuangfj2:$HF_TOKEN@huggingface.co/csukuangfj2/sherpa-onnx-harmony-os main


  docker-1:
    if: false
    # see https://gitee.com/openharmony/docs/blob/master/zh-cn/device-dev/get-code/gettools-acquire.md
    name: docker
    runs-on: ${{ matrix.os }}
    container: swr.cn-south-1.myhuaweicloud.com/openharmony-docker/openharmony-docker:1.0.0
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      # - uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0
      #
      # - name: Update version
      #   shell: bash
      #   run: |
      #     ./new-release.sh
      #     git diff .

      - name: Setup tmate session
        # if: true
        # if: failure()
        uses: mxschmitt/action-tmate@v3

  docker-2:
    name: docker-2
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update version
        shell: bash
        run: |
          ./new-release.sh
          git diff .

      - name: Run docker
        uses: addnab/docker-run-action@v3
        with:
            image: swr.cn-south-1.myhuaweicloud.com/openharmony-docker/openharmony-docker:1.0.0
            options: |
              --volume ${{ github.workspace }}/:/sherpa-onnx
            shell: bash
            run: |
              ls
              cd /
              find / -name "hvigorw" 2>/dev/null

