name: hos-har

on:
  push:
    branches:
      - ohos-arm32
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

  workflow_dispatch:

concurrency:
  group: hos-har-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-libs:
    name: hos ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64-v8a, x86-64]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update version
        shell: bash
        run: |
          ./new-release.sh

      - name: Get version
        shell: bash
        run: |
          SHERPA_ONNX_VERSION=$(grep "SHERPA_ONNX_VERSION" ./CMakeLists.txt | cut -d " " -f 2 | cut -d '"' -f 2)
          echo "SHERPA_ONNX_VERSION=$SHERPA_ONNX_VERSION" >> "$GITHUB_ENV"

      - name: Cache build result for ${{ matrix.arch }}
        id: cache-build-result
        uses: actions/cache@v4
        with:
          path: artifact
          key: sherpa-onnx-hos-libs-${{ matrix.arch }}-${{ env.SHERPA_ONNX_VERSION }}-cache-v1

      - name: cache-toolchain (CPU)
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: command-line-tools
          key: commandline-tools-linux-x64-5.0.3.906.zip

      - name: Download toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        shell: bash
        run: |
          v=5.0.3.906
          # curl -SL -O https://huggingface.co/csukuangfj/harmonyos-commandline-tools/resolve/main/commandline-tools-linux-x64-$v.zip

          BASE_URL="https://github.com/csukuangfj/test-github-actions/releases/download/ohos-tools"
          for i in 00 01 02; do
            curl -L -O "${BASE_URL}/commandline-tools-part${i}"
          done

          cat commandline-tools-part00 commandline-tools-part01 commandline-tools-part02 > commandline-tools-linux-x64-5.0.3.906.zip

          unzip commandline-tools-linux-x64-5.0.3.906.zip > /dev/null
          rm commandline-tools-linux-x64-5.0.3.906.zip
          rm -v commandline*part*

      - name: Set environment variable
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          echo "$GITHUB_WORKSPACE/command-line-tools/sdk/default/openharmony/native/build-tools/cmake/bin"  >> "$GITHUB_PATH"

      - name: Patch toolchain file
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          toolchain_file=$GITHUB_WORKSPACE/command-line-tools/sdk/default/openharmony/native/build/cmake/ohos.toolchain.cmake
          sed -i.bak 's/set(UNIX TRUE CACHE BOOL FROCE)/set(UNIX TRUE CACHE BOOL "Force UNIX" FORCE)/g' $toolchain_file

          sed -i.bak s/CMAKE_SYSTEM_NAME\ OHOS/CMAKE_SYSTEM_NAME\ Linux/g $toolchain_file
          sed -i.bak 's/set(CMAKE_C_FLAGS "${OHOS_C_COMPILER_FLAGS} ${CMAKE_C_FLAGS} -D__MUSL__")/set(CMAKE_C_FLAGS "${OHOS_C_COMPILER_FLAGS} ${CMAKE_C_FLAGS} -D__MUSL__ -D__OHOS__")/' $toolchain_file
          sed -i.bak 's/set(CMAKE_CXX_FLAGS "${OHOS_CXX_COMPILER_FLAGS} ${CMAKE_CXX_FLAGS} -D__MUSL__")/set(CMAKE_CXX_FLAGS "${OHOS_CXX_COMPILER_FLAGS} ${CMAKE_CXX_FLAGS} -D__MUSL__ -D__OHOS__")/' $toolchain_file

      - name: ccache
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: hos-har-linux-${{ matrix.arch }}

      - name: Build libraries
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          export CMAKE_CXX_COMPILER_LAUNCHER=ccache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          cmake --version

          export OHOS_SDK_NATIVE_DIR="$GITHUB_WORKSPACE/command-line-tools/sdk/default/openharmony/native"
          export SHERPA_ONNX_HARMONY_OS_TYPE=hos

          arch=${{ matrix.arch }}
          if [ $arch == arm64-v8a ]; then
            ./build-ohos-arm64-v8a.sh
          elif [ $arch == x86-64 ]; then
            ./build-ohos-x86-64.sh
          fi

      - name: Collect libs
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          arch=${{ matrix.arch }}
          if [ $arch == arm64-v8a ]; then
            build_dir=build-ohos-arm64-v8a
          elif [ $arch == x86-64 ]; then
            build_dir=build-ohos-x86-64
          fi

          mkdir -p artifact
          cp -v $build_dir/install/lib/libsherpa-onnx-c-api.so artifact/
          cp -v $build_dir/install/lib/libonnxruntime.so artifact/

      - uses: actions/upload-artifact@v4
        with:
          name: sherpa-onnx-hos-libs-${{ matrix.arch }}
          path: ./artifact/

  build-har:
    name: Build HOS Har
    needs: [build-libs]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update version
        shell: bash
        run: |
          ./new-release.sh

      - name: cache-toolchain
        id: cache-toolchain-hos
        uses: actions/cache@v4
        with:
          path: command-line-tools
          key: commandline-tools-linux-x64-5.0.3.906.zip

      - name: Download toolchain
        if: steps.cache-toolchain-hos.outputs.cache-hit != 'true'
        shell: bash
        run: |
          BASE_URL="https://github.com/csukuangfj/test-github-actions/releases/download/ohos-tools"
          for i in 00 01 02; do
            curl -L -O "${BASE_URL}/commandline-tools-part${i}"
          done

          cat commandline-tools-part00 commandline-tools-part01 commandline-tools-part02 > commandline-tools-linux-x64-5.0.3.906.zip

          unzip commandline-tools-linux-x64-5.0.3.906.zip > /dev/null
          rm commandline-tools-linux-x64-5.0.3.906.zip
          rm -v commandline*part*

      - name: Retrieve artifact (arm64-v8a)
        uses: actions/download-artifact@v4
        with:
          name: sherpa-onnx-hos-libs-arm64-v8a
          path: ./harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/libs/arm64-v8a

      - name: Retrieve artifact (x86_64)
        uses: actions/download-artifact@v4
        with:
          name: sherpa-onnx-hos-libs-x86-64
          path: ./harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/libs/x86_64

      - name: Display libs
        shell: bash
        run: |
          echo "---arm64-v8a---"
          ls -lh ./harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/libs/arm64-v8a/

          echo "---x86_64---"
          ls -lh ./harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/libs/x86_64/

      - name: Build Har
        shell: bash
        run: |
          export PATH="$GITHUB_WORKSPACE/command-line-tools/bin:$PATH"

          which hvigorw

          pushd harmony-os/SherpaOnnxHar

          cp -fv ../../LICENSE ./sherpa_onnx
          cp -fv ../../CHANGELOG.md ./sherpa_onnx

          hvigorw --mode module -p product=default -p module=sherpa_onnx@default assembleHar --analyze=normal --parallel --incremental --no-daemon
          ls -lh ./sherpa_onnx/build/default/outputs/default/sherpa_onnx.har

          popd

          cp -v ./harmony-os/SherpaOnnxHar/sherpa_onnx/build/default/outputs/default/sherpa_onnx.har $GITHUB_WORKSPACE/sherpa_onnx_hos.har

          ls -lh $GITHUB_WORKSPACE/*.har

      - name: View Har
        shell: bash
        run: |
          file sherpa_onnx_hos.har
          mkdir -p view-har && cd view-har
          tar xzf $GITHUB_WORKSPACE/sherpa_onnx_hos.har

          cd package
          ls -lh

          ls -lh libs
          echo "---libs/x86_64---"
          ls -lh libs/x86_64

          echo "---libs/arm64-v8a---"
          ls -lh libs/arm64-v8a

          echo "---src/main/ets/components---"
          ls -lh src/main/ets/components/

          echo "---src/main/cpp/types/libsherpa_onnx/---"
          ls -lh src/main/cpp/types/libsherpa_onnx/

          sudo apt-get install -y -q tree
          tree .

      - name: Collect result
        shell: bash
        run: |
          SHERPA_ONNX_VERSION=v$(grep "SHERPA_ONNX_VERSION" ./CMakeLists.txt  | cut -d " " -f 2  | cut -d '"' -f 2)
          echo "SHERPA_ONNX_VERSION=$SHERPA_ONNX_VERSION" >> "$GITHUB_ENV"

          mv sherpa_onnx_hos.har sherpa_onnx_hos-$SHERPA_ONNX_VERSION.har

      - uses: actions/upload-artifact@v4
        with:
          name: sherpa-onnx-hos-har
          path: ./sherpa_onnx_hos*.har

      - name: Release har
        # if: (github.repository_owner == 'csukuangfj' || github.repository_owner == 'k2-fsa') && github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          overwrite: true
          file: ./*.har
          repo_name: k2-fsa/sherpa-onnx
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: v1.13.3

      - name: Publish to huggingface
        if: (github.repository_owner == 'csukuangfj' || github.repository_owner == 'k2-fsa') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        uses: nick-fields/retry@v3
        with:
          max_attempts: 20
          timeout_seconds: 200
          shell: bash
          command: |
            git config --global user.email "csukuangfj@gmail.com"
            git config --global user.name "Fangjun Kuang"

            rm -rf huggingface
            export GIT_LFS_SKIP_SMUDGE=1
            export GIT_CLONE_PROTECTION_ACTIVE=false

            SHERPA_ONNX_VERSION=$(grep "SHERPA_ONNX_VERSION" ./CMakeLists.txt  | cut -d " " -f 2  | cut -d '"' -f 2)
            echo "SHERPA_ONNX_VERSION $SHERPA_ONNX_VERSION"

            git clone https://csukuangfj2:$HF_TOKEN@huggingface.co/csukuangfj2/sherpa-onnx-harmony-os huggingface
            cd huggingface
            git fetch
            git pull
            git merge -m "merge remote" --ff origin main

            d=har
            mkdir -p $d
            cp -v ../*.har $d/
            git status
            git lfs track "*.har"
            git add .
            git commit -m "add more hars"
            git push https://csukuangfj2:$HF_TOKEN@huggingface.co/csukuangfj2/sherpa-onnx-harmony-os main
